# Site settings
title: Ken Xu Classic Games Remake
email: colinxu@usc.edu/602772678colin@gmail.com
description: > # keep this and put description below
  I am a Junior College Student studying Computer Science Game at USC. I have been playing games since the age of 5 and love every aspect of them. I think there is nothing more beautiful and satisfying than to see so many elements - music, scenery, dialog - all come together to make memories players will not forget. I am especially interested Gameplay design and engineering, as I have worked on several video games as a Gameplay engineer. At this site you will see some of the game projects I have worked on. 

url: https://colinxuxuxu.github.io
linkedin_url: www.linkedin.com/in/ken-xu-a697a6289
github_username: colinxuxuxu
twitter_username: gamingportfolio
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
