# Site settings
title: Ken Xu Classic Games Remake
email: colinxu@usc.edu/602772678colin@gmail.com
description: > # keep this and put description below
  I am a Junior College Student studying Computer Science Game at USC, Gameplay Engineer/Designer.
url: https://colinxuxuxu.github.io
linkedin_url: www.linkedin.com/in/ken-xu-a697a6289
github_username: colinxuxuxu
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
